personal_portfolio_project/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),    
]

personal_portfolio_project/personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal_portfolio_project/blog/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=250)
    date = models.DateField()
    description = models.TextField(max_length=500)

personal_portfolio_project/portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=140)
    description = models.CharField(max_length=300)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

personal_portfolio_project/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

def all_blogs(request):
    blogs = Blog.objects.all()
    return render(request, 'blog/all_blogs.html', {'blogs':blogs});

def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog':blog})

personal_portfolio_project/portfolio/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request,'portfolio/home.html', {'projects':projects})

personal_portfolio_project/blog/templates/blog/all_blogs.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

<h1>Blog</h1>


{% for blog in blogs %}

<a href"{% url 'blog:detail' blog.id %}"><h2>{{ blog.title }}</h2></a>
<h3>{{ blog.date }}</h3>
<p>{{ blog.post }}</p>

{% endfor %}

<a href="{% url 'home' %}">Return to Homepage</a>

personal_portfolio_project/blog/templates/blog/detail.html
{{ blog.title }}

personal_portfolio_project/portfolio/templates/portfolio/home.html
{% load static %}
<h1>This is HOMEEEEEE!!!</h1>

<a href="{% static 'portfolio/Django_The_Right_Way.pdf' %}">Django The Right Way PDF</a>

<div name="container">
<img src={% static 'portfolio/jordan.jpg' %}

{% for project in projects %}

<h1>{{ project.title }}</h1>
<h3>{{ project.description }}</h3>
<img src="{{ project.image.url }}"></img>
{% if project.url %}
<p><a href="{{ project.url }}">Link to Project</a></p>
{% endif %}
{% endfor %}
</div>